### ISSUE TITLE
Panic on PartialEq

### ISSUE THREAD

**Issue by jeromegn** [andreacorbellini/rust-circular-buffer#7]
This line can (always?) panic: https://github.com/andreacorbellini/rust-circular-buffer/blob/c66289601a23c25e1adc15ea6f99f269eeeae952/src/lib.rs#L1780

```
thread 'tokio-runtime-worker' panicked at 'range start index 7 out of range for slice of length 0', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/circular-buffer-0.1.5/src/lib.rs:1780:46
```

**Comment by andreacorbellini** [comment]
Thanks for reporting this bug! Indeed, the logic in the condition was wrong (likely the result of a wrong copy-and-paste).

This has been fixed in ee64dfc81e31c2ae6bd2dc321d8225456329463d and released in [circular-buffer 0.1.6](https://crates.io/crates/circular-buffer/0.1.6).
